apiVersion: v2
name: accounting-chart
description: A Helm chart for Kubernetes

type: application

version: 0.1.0
appVersion: "v23"


dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - accounting-database