replicaCount: 1

metrics:
  serviceMonitor:
    enabled: true
# fullnameOverride: "accounting"

image:
  repository: bael/ms-course-accounting

service:
  type: NodePort
  port: 9000


postgresql:
  metrics:
  enabled: true
  # resources: {}
  service:
    type: ClusterIP
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9187"
    loadBalancerIP:
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 30s
    scrapeTimeout: 10s
  enabled: true
  fullnameOverride: accounting-postgresql 
  postgresqlUsername: postgres
  postgresqlPassword: password
  postgresqlDatabase: accounting
  persistence:
    size: 1Gi
  service:
    port: "5432"

