apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
data:
  POSTGRES_URL: "jdbc:postgresql://{{.Values.postgresql.fullnameOverride}}:5432/{{.Values.postgresql.postgresqlDatabase}}"
  LOGGING_LEVEL: DEBUG
  KAFKA_URL: "bootstrap.kafka.svc.cluster.local:9092"
  ENABLE_HAZELCAST_KUBERNETES: "true"
  

---
apiVersion: v1
kind: Secret
metadata:
  name: inventory-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}

