databaseChangeLog:
  - include:
      file: db/changelog/v1/init-inventory-table.xml
  - include:
      file: db/changelog/v1/init-sequence.xml
  - include:
      file: db/changelog/v1/add-sku-items.xml
  - include:
      file: db/changelog/v1/init-inbox-table.xml
  - include:
      file: db/changelog/v1/init-outbox-table.xml
