apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
data:
  POSTGRES_URL: "jdbc:postgresql://{{.Values.postgresql.fullnameOverride}}:5432/{{.Values.postgresql.postgresqlDatabase}}"
  LOGGING_LEVEL: DEBUG
  KAFKA_URL: "bootstrap.kafka.svc.cluster.local:9092"

---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}

