replicaCount: 1

fullnameOverride: "auth"

metrics:
  serviceMonitor:
    enabled: true

image:
  repository: bael/ms-course-auth

service:
  type: NodePort
  port: 9000

postgresql:
  metrics:
    enabled: true
    # resources: {}
    service:
      type: ClusterIP
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
      loadBalancerIP:
    serviceMonitor:
      enabled: true
      namespace: monitoring
      interval: 30s
      scrapeTimeout: 10s  
  enabled: true
  fullnameOverride: auth-postgresql
  postgresqlUsername: postgres
  postgresqlPassword: password
  postgresqlDatabase: auth
  persistence:
    size: 0.1Gi
  service:
    port: "5432"

ingress:
  enabled: false
  hosts:
    - host: arch.homework
      paths: ["/auth"]
