replicaCount: 1

fullnameOverride: "auth"

image:
  repository: bael/ms-course-auth

service:
  type: NodePort
  port: 9000

postgresql:
  enabled: true
  fullnameOverride: auth-postgresql
  postgresqlUsername: postgres
  postgresqlPassword: password
  postgresqlDatabase: auth
  persistence:
    size: 0.1Gi
  service:
    port: "5432"

ingress:
  enabled: false
  hosts:
    - host: arch.homework
      paths: ["/auth"]
