apiVersion: batch/v1
kind: Job
metadata:
  name: shop-initdb
spec:
  template:
    metadata:
      name: shop-initdb
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: shop-secret
                key: POSTGRES_USER
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: shop-secret
                key: POSTGRES_PASSWORD
          - name: DATABASE_URI
            value: "postgresql://postgres/shop"
        image: postgres:latest
        command:
          - sh
          - "-c"
          - |
            psql -h postgres -p 5432 --username=$POSTGRES_USER -d shop <<'EOF' 
              CREATE SEQUENCE IF NOT EXISTS serial START 1;
              drop table users;
              create table users (id bigint PRIMARY KEY DEFAULT nextval('serial'), first_name text, last_name text, email text, phone text);
              insert into users (id, first_name, last_name, email, phone) values (1, 'First', 'second', 'noemail@email.email', '223322');
            EOF
  backoffLimit: 2
