apiVersion: v2
name: shop-chart
description: A Helm chart for Kubernetes
fullname: myshop-service
type: application

version: 0.4.0
appVersion: "v4"

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - shop-database
