{
 "title": "myshop_dasboard_panel",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
   },
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\"}[1m]))",
     "legendFormat": "rps"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"5..\"}[1m]))",
     "legendFormat": "errors HTTP - 5xx"
    }
   ]
  },
  {
   "title": "ERRORS/S",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"myshop\", status=~\"5..\"}[1m]))",
     "legendFormat": "HTTP - 5xx"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage by pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{pod=~\".*shop-chart.*\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests_cpu_cores{pod=~\".*shop-chart.*\"})\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits_cpu_cores{pod=~\".*shop-chart.*\"})\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Latency percentile .5",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, userId) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/{userId}\"}[5m]))) ",
     "legendFormat": "{{instance}} .5 percentile /api/v1/user/{userId}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le, userId) (rate(http_server_requests_seconds_bucket{uri=\"/actuator/prometheus\"}[5m]))) \n",
     "legendFormat": "{{instance}} .5 percentile /metrics/"
    }
   ]
  },
  {
   "title": "Memory Usage by pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes {pod=~\".*shop-chart.*\"})\n\n",
     "legendFormat": "{{pod }} memory consumption"
    },
    {
     "expr": "sum  (\n    kube_pod_container_resource_requests_memory_bytes{pod=~\".*shop-chart.*\"})\n",
     "legendFormat": "memory requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits_memory_bytes{pod=~\".*shop-chart.*\"})\n",
     "legendFormat": "memory limits"
    }
   ]
  },
  {
   "title": "Latency percentile max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (le, userId) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/{userId}\"}[5m]))) ",
     "legendFormat": "{{instance}} .5 percentile /api/v1/user/{userId}"
    },
    {
     "expr": "histogram_quantile(1, sum by (le, userId) (rate(http_server_requests_seconds_bucket{uri=\"/actuator/prometheus\"}[5m]))) \n",
     "legendFormat": "{{instance}} .5 percentile /metrics/"
    }
   ]
  },
  {
   "title": "Latency percentile .95",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, userId) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/{userId}\"}[5m]))) ",
     "legendFormat": "{{instance}} .5 percentile /api/v1/user/{userId}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, userId) (rate(http_server_requests_seconds_bucket{uri=\"/actuator/prometheus\"}[5m]))) \n",
     "legendFormat": "{{instance}} .5 percentile /metrics/"
    }
   ]
  },
  {
   "title": "RPS (ingress)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_service) (rate(nginx_ingress_controller_requests{exported_service=~\".*shop-chart.*\"}[1m]))\n\n"
    }
   ]
  },
  {
   "title": "Latency percentile .99",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, userId) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/{userId}\"}[5m]))) ",
     "legendFormat": "{{instance}} .5 percentile /api/v1/user/{userId}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, userId) (rate(http_server_requests_seconds_bucket{uri=\"/actuator/prometheus\"}[5m]))) \n",
     "legendFormat": "{{instance}} .5 percentile /metrics/"
    }
   ]
  },
  {
   "title": "Errros RPS (ingress)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_service) (rate(nginx_ingress_controller_requests{exported_service=~\".*shop-chart.*\", status=~\"[4-5].*\"}[1m]))\n\n",
     "legendFormat": "error rps by ingress"
    }
   ]
  },
  {
   "title": "Latency all percentiles",
   "type": "graph",
   "description": "Все перцентили на одной диаграмме",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, url) (rate(http_server_requests_seconds_bucket[5m]))) ",
     "legendFormat": "{{instance}} .5 percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, url) (rate(http_server_requests_seconds_bucket[5m]))) \n",
     "legendFormat": "{{instance}} .95 percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, url) (rate(http_server_requests_seconds_bucket[5m]))) \n",
     "legendFormat": "{{instance}} .99 percentile"
    },
    {
     "expr": "histogram_quantile(1, sum by (le, url) (rate(http_server_requests_seconds_bucket[5m]))) \n",
     "legendFormat": "{{instance}} max percentile"
    }
   ]
  },
  {
   "title": "balancing view",
   "type": "graph",
   "description": "как распределяется нагрузка между инстанцами",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(http_server_requests_seconds_count{application=\"$application\"}[1m]))"
    }
   ]
  },
  {
   "title": "postgres is up",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pg_up\n" }
   ]
  },
  {
   "title": "postgres stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{datname=\"shop\"}[5m])"
    },
    {
     "expr": "sum(pg_locks_count{datname=\"shop\"}) \n",
     "legendFormat": "pg_locs_count"
    },
    {
     "expr": "rate(pg_stat_database_tup_returned{datname=\"shop\"}[5m])",
     "legendFormat": "records returned per second"
    },
    {
     "expr": "rate(pg_stat_database_blk_read_time{datname=\"shop\"}[5m])",
     "legendFormat": "read time"
    },
    {
     "expr": "rate(pg_stat_database_blks_hit{datname=\"shop\"}[5m])",
     "legendFormat": "cache hit rate"
    }
   ]
  }
 ]
}