apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-config
data:
  POSTGRES_URL: jdbc:postgresql://postgres:5432/shop
---
apiVersion: v1
kind: Secret
metadata:
  name: shop-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: bWVnQHBhc3N3b3Jk