apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
data:
  POSTGRES_URL: "jdbc:postgresql://{{.Values.postgresql.fullnameOverride}}:5432/{{.Values.postgresql.postgresqlDatabase}}"
  LOGGING_LEVEL: DEBUG
  KAFKA_URL: "bootstrap.kafka.svc.cluster.local:9092"
  INVENTORY_SERVICE_URL: "http://inventory-inventory-chart.monitoring.svc.cluster.local:9000"
  

---
apiVersion: v1
kind: Secret
metadata:
  name: orders-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}

