replicaCount: 1

# fullnameOverride: "accounting"
metrics:
  serviceMonitor:
    enabled: true

image:
  repository: bael/ms-course-history

service:
  type: NodePort
  port: 9000


postgresql:
  metrics:
    enabled: true
    # resources: {}
    service:
      type: ClusterIP
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
      loadBalancerIP:
    serviceMonitor:
      enabled: true
      namespace: monitoring
      interval: 30s
      scrapeTimeout: 10s  
  enabled: true
  fullnameOverride: history-postgresql 
  postgresqlUsername: postgres
  postgresqlPassword: password
  postgresqlDatabase: history
  persistence:
    size: 1Gi
  service:
    port: "5432"

